"""Hand-written convenience factory around the generated `Client` /
`AuthenticatedClient` (nuance_client/client.py, generated by
`openapi-python-client` from ../../openapi.json — see ../generate.sh and
never edited directly). Mirrors ../../typescript/src/client.ts's
`createNuanceClient`: one call configures the base URL and whichever
credential(s) apply, sized to backend/app/dependencies.py's own precedence
(X-Api-Key checked first, exclusively, if present; JWT bearer otherwise).

Two credential shapes:
  - `api_key`: for non-browser/agent callers (ROADMAP.md Part 4 6.1). Sent
    as a default `X-Api-Key` header on every request via the base `Client`'s
    own `headers=` constructor kwarg — this works even though the
    generator also emits a per-call `x_api_key` kwarg on each scoped
    operation (see create_escrow_escrows_post.py etc.), because that field
    is a bare FastAPI `Header(...)` parameter, not a registered OpenAPI
    security scheme (see app/dependencies.py's own docstring on why), so
    the generator can't wire it up as connection-level auth by itself the
    way it does for the JWT bearer scheme below. Setting it as a default
    header here means a caller never has to pass `x_api_key=` to every
    individual call.
  - `access_token`: the wallet-signature JWT from `POST /auth/verify`'s
    `access_token` field. This DOES map to a registered `HTTPBearer`
    security scheme, so it uses the generator's own `AuthenticatedClient`
    (token + prefix="Bearer" -> `Authorization: Bearer <token>` on every
    request that scheme applies to).

A caller needing both (e.g. an agent that also wants to call the
JWT-only-guarded routes, like `/disputes/{id}/enforce`) can pass both;
each request only ever uses the one its own generated function was built
for.
"""

from __future__ import annotations

from nuance_client.client import AuthenticatedClient, Client


def create_nuance_client(
    base_url: str,
    *,
    api_key: str | None = None,
    access_token: str | None = None,
) -> Client | AuthenticatedClient:
    """Returns a `Client` (api_key and/or anonymous) or `AuthenticatedClient`
    (access_token given) ready to pass as the `client=` argument to any
    generated `nuance_client.api.*` function.

    `base_url`: e.g. "https://api.nuance.example" or "http://localhost:8000"
    — no trailing slash needed, matches every path in openapi.json starting
    with "/".
    """
    headers = {"X-Api-Key": api_key} if api_key else {}

    if access_token:
        return AuthenticatedClient(base_url=base_url, token=access_token, headers=headers)
    return Client(base_url=base_url, headers=headers)
