"""baseline

Revision ID: 0a53bda4446e
Revises: 
Create Date: 2026-09-07 20:39:53.740928

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a53bda4446e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consensus_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_type', sa.Enum('MILESTONE', 'DISPUTE', name='consensussubjecttype'), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('validator_results', sa.JSON(), nullable=True),
    sa.Column('verdict_label', sa.String(), nullable=True),
    sa.Column('verdict_approved', sa.Boolean(), nullable=True),
    sa.Column('verdict_confidence', sa.Integer(), nullable=True),
    sa.Column('verdict_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('resolution_date', sa.DateTime(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('status_key', sa.String(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('resolution_reasoning', sa.Text(), nullable=True),
    sa.Column('resolution_source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('chain_status', sa.Enum('LEGACY_OFFCHAIN', 'PROCESSING', 'DECIDED', 'FINALIZED', 'CANCELED', name='chainstatus'), nullable=False),
    sa.Column('on_chain_raw_status', sa.String(), nullable=True),
    sa.Column('on_chain_tx_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('nonce_issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('wallet_address')
    )
    op.create_table('escrows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_address', sa.String(), nullable=False),
    sa.Column('counterparty_address', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status_key', sa.Enum('APPROVED', 'IN_REVIEW', 'IN_PROGRESS', 'PENDING', 'DISPUTED', 'REJECTED', name='statuskey'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_address'], ['users.wallet_address'], ),
    sa.ForeignKeyConstraint(['creator_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('user_address', sa.String(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'user_address', 'endpoint', name='uq_idempotency_key_user_endpoint')
    )
    op.create_table('market_event_log',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('prediction_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['wallet_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('proposer_address', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PASSED', 'REJECTED', 'EXECUTED', name='proposalstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('quorum_threshold', sa.Integer(), nullable=False),
    sa.Column('pass_threshold', sa.Integer(), nullable=False),
    sa.Column('total_for', sa.Integer(), nullable=False),
    sa.Column('total_against', sa.Integer(), nullable=False),
    sa.Column('total_abstain', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.wallet_address'], ),
    sa.ForeignKeyConstraint(['proposer_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('notify_on', sa.Boolean(), nullable=False),
    sa.Column('auto_escalate_on', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('wallet_address')
    )
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status_key', sa.Enum('APPROVED', 'IN_REVIEW', 'IN_PROGRESS', 'PENDING', 'DISPUTED', 'REJECTED', name='statuskey'), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('on_chain_index', sa.Integer(), nullable=True),
    sa.Column('chain_status', sa.Enum('LEGACY_OFFCHAIN', 'PROCESSING', 'DECIDED', 'FINALIZED', 'CANCELED', name='chainstatus'), nullable=False),
    sa.Column('on_chain_raw_status', sa.String(), nullable=True),
    sa.Column('on_chain_tx_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('voter_address', sa.String(), nullable=False),
    sa.Column('choice', sa.Enum('FOR', 'AGAINST', 'ABSTAIN', name='votechoice'), nullable=False),
    sa.Column('voting_power', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['voter_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'voter_address', name='uq_votes_proposal_voter')
    )
    op.create_table('deliverable_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['wallet'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('escrow_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('opened_by_address', sa.String(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('status_key', sa.Enum('APPROVED', 'IN_REVIEW', 'IN_PROGRESS', 'PENDING', 'DISPUTED', 'REJECTED', name='statuskey'), nullable=False),
    sa.Column('ruling', sa.Text(), nullable=True),
    sa.Column('enforced_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('on_chain_dispute_id', sa.Integer(), nullable=True),
    sa.Column('chain_status', sa.Enum('LEGACY_OFFCHAIN', 'PROCESSING', 'DECIDED', 'FINALIZED', 'CANCELED', name='chainstatus'), nullable=False),
    sa.Column('on_chain_raw_status', sa.String(), nullable=True),
    sa.Column('on_chain_tx_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['enforced_by'], ['users.wallet_address'], ),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ),
    sa.ForeignKeyConstraint(['opened_by_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispute_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('submitter_address', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.ForeignKeyConstraint(['submitter_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispute_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('sender_address', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.ForeignKeyConstraint(['sender_address'], ['users.wallet_address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispute_messages')
    op.drop_table('dispute_evidence')
    op.drop_table('disputes')
    op.drop_table('deliverable_submissions')
    op.drop_table('votes')
    op.drop_table('milestones')
    op.drop_table('user_settings')
    op.drop_table('proposals')
    op.drop_table('prediction_positions')
    op.drop_table('market_event_log')
    op.drop_table('idempotency_records')
    op.drop_table('escrows')
    op.drop_table('users')
    op.drop_table('predictions')
    op.drop_table('consensus_jobs')
    # ### end Alembic commands ###
