"""add funded/adjudication/resolution-trigger tx hash columns

Revision ID: 89e8507ee4e7
Revises: 0a53bda4446e
Create Date: 2026-09-08 10:28:58.430907

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e8507ee4e7'
down_revision: Union[str, None] = '0a53bda4446e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('adjudication_tx_hash', sa.String(), nullable=True))
    op.add_column('escrows', sa.Column('funded_tx_hash', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('resolution_trigger_tx_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'resolution_trigger_tx_hash')
    op.drop_column('escrows', 'funded_tx_hash')
    op.drop_column('disputes', 'adjudication_tx_hash')
    # ### end Alembic commands ###
