"""add escrows.cancelled_tx_hash

Revision ID: c3348d65435d
Revises: 89e8507ee4e7
Create Date: 2026-09-08 12:57:26.749305

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3348d65435d'
down_revision: Union[str, None] = '89e8507ee4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escrows', sa.Column('cancelled_tx_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escrows', 'cancelled_tx_hash')
    # ### end Alembic commands ###
