"""add milestones.released_at

Revision ID: eac90fe5a4f5
Revises: fc8e8055061b
Create Date: 2026-09-08 18:40:37.742318

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac90fe5a4f5'
down_revision: Union[str, None] = 'fc8e8055061b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('released_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'released_at')
    # ### end Alembic commands ###
