"""add milestones.reasoning

Revision ID: fc8e8055061b
Revises: c3348d65435d
Create Date: 2026-09-08 15:55:06.625096

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8e8055061b'
down_revision: Union[str, None] = 'c3348d65435d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'reasoning')
    # ### end Alembic commands ###
