#!/usr/bin/env bash
# Regenerates both SDKs from ONE OpenAPI spec (ROADMAP.md Part 4 6.3):
#   1. Export ../backend/app/main.py's live FastAPI schema to openapi.json
#      (no server needs to be running — see ../backend/scripts/export_openapi.py).
#   2. Regenerate the TypeScript client (typescript/src/generated/) via
#      @hey-api/openapi-ts.
#   3. Regenerate the Python client (python/nuance-client/nuance_client/) via
#      openapi-python-client.
#
# Run from anywhere; paths below are relative to this script's own location.
# Requires: backend/.venv already set up (see backend/README or just
# `python -m venv .venv && .venv/bin/pip install -r requirements.txt`),
# and `npm install` already run once in sdk/typescript/.
#
# Neither generated output tree is .gitignore'd — both are checked in (see
# README.md) so `npm install @nuance/sdk` / `pip install nuance-client`
# works for a consumer with no codegen step of their own, same reasoning
# the backend's own committed Alembic migrations aren't regenerated by
# every consumer either. Re-run this script and commit the diff whenever
# the backend's routes/schemas change.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

BACKEND_VENV_PYTHON="../backend/.venv/bin/python"
if [ ! -x "$BACKEND_VENV_PYTHON" ]; then
  echo "error: $BACKEND_VENV_PYTHON not found — set up backend/.venv first." >&2
  exit 1
fi

echo "==> 1/3 Exporting OpenAPI spec from the FastAPI app..."
(cd ../backend && .venv/bin/python -m scripts.export_openapi ../sdk/openapi.json)

echo "==> 2/3 Regenerating TypeScript client..."
(cd typescript && npm run generate && npm run build)

echo "==> 3/3 Regenerating Python client..."
(cd python && "../../backend/.venv/bin/openapi-python-client" generate \
  --path ../openapi.json \
  --config openapi-python-client-config.yaml \
  --meta poetry \
  --overwrite)

echo "==> Done. Review the diff under sdk/ before committing —"
echo "    a route/schema change upstream can rename generated functions/types."
